FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y python3 python3-pip curl vim git
RUN pip3 install flask requests --break-system-packages

COPY . /app
WORKDIR /app

ENV DB_PASSWORD=supersecret123

EXPOSE 5000

CMD python3 app.py
