apiVersion: v1
kind: Pod
metadata:
  name: tolerates
spec:
  tolerations:
  - key: "demo"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx
